export type JobPostingStatus = "posted" | "draft" | "closed";

export type JobPosting = {
  jobPostingId: string;
  wantedJobId?: number;
  wantedSourceUrl?: string;
  companyId: string;
  companyName?: string;
  recruiterId: string;
  title: string;
  industry: string;
  jobCategory: string;
  jobTitle: string;
  employmentType: string;
  experienceLevel: string;
  experienceMin: number | null;
  experienceMax: number | null;
  requiredSkills: string[];
  workType: string;
  flexibleWorkTypes: string[];
  workDays: string[];
  salaryType: string;
  salaryText: string;
  locationType: string;
  address: string;
  roadAddress: string;
  jibunAddress: string;
  sourceWantedAddress?: string;
  location: {
    lat: number;
    lng: number;
  } | null;
  primaryStationName: string;
  stationWalkMinutes?: number;
  workTimeText?: string;
  applicationPeriod?: string;
  mainResponsibilities: string;
  requirements?: string[];
  preferences?: string[];
  hiringProcess?: string[];
  assignmentTitle?: string;
  assignmentSummary?: string;
  assignmentIds: string[];
  hasAssignment: boolean;
  status: JobPostingStatus;
  createdAt: string;
  updatedAt: string;
  postedAt: string | null;
  closedAt: string | null;
  isRecommended?: boolean;
  applicantCount?: number;
};
